#![no_std]
//! The Orbita application SDK — the crate applications compile against.
//!
//! An Orbita application is a `#![no_std]` Rust binary for
//! `x86_64-unknown-none`, statically linked at the Orbita app base
//! address. The single entry point is generated by [`entry!`]:
//!
//! ```ignore
//! // apps/examples/hello/src/main.rs
//! #![no_std]
//! #![no_main]
//!
//! use orbita_sdk::println;
//! use orbita_sdk::sys::fs;
//!
//! orbita_sdk::entry! {
//!     fn main() -> i32 {
//!         println!("hello from a native rust app");
//!         fs::write("/tmp/visited", b"hello").ok();
//!         0
//!     }
//! }
//! ```
//!
//! The kernel calls `orb_main(&OrbAbi)` with the ABI function table;
//! [`abi::install`] stores it and every [`sys`] call goes through it.
//! The SDK also installs the [`GlobalAlloc`](core::alloc::GlobalAlloc) that services the
//! application's `alloc` (`String`/`Vec`/...) through the same table.
//!
//! Build & package with `orbita-build` (`dm alias pkgbuild`), install
//! inside the OS with `pkg install <name>`, run with `run <name>`.

extern crate alloc;

pub mod abi;
pub mod sys;

/// Entry-point generator: wraps `fn main() -> i32` in the C-ABI
/// `orb_main` the kernel loader calls.
///
/// A code passed to [`sys::process::exit`] overrides the returned value.
/// The final EXIT syscall terminates ring-3 execution immediately (and
/// merely records the code for the ring-0 exec path).
#[macro_export]
macro_rules! entry {
    (fn main() -> i32 $body:block) => {
        #[unsafe(no_mangle)]
        pub extern "C" fn orb_main(abi: *const $crate::abi::OrbAbi) -> i32 {
            unsafe { $crate::abi::install(abi) };
            let returned: i32 = $body;
            let code = $crate::abi::take_exit_code().unwrap_or(returned);
            let _ = $crate::abi::call($crate::abi::nr::EXIT, code as u32 as u64, 0, 0, 0);
            code
        }
    };
}

/// Format helper used by [`println!`] (keeps `alloc` out of app scopes).
#[doc(hidden)]
pub fn __format(args: core::fmt::Arguments<'_>) -> alloc::string::String {
    alloc::fmt::format(args)
}

/// `println!` for applications: formats to a heap
/// [`String`](alloc::string::String) and emits one stdout line through
/// the ABI.
#[macro_export]
macro_rules! println {
    () => { $crate::println!("") };
    ($($arg:tt)*) => {
        $crate::abi::stdout_line(&$crate::__format(format_args!($($arg)*)))
    };
}

/// Application panic handler: report through stdout, then exit.
///
/// In ring 3 the EXIT syscall unwinds into the kernel, which continues
/// the boot/shell loop — an application panic no longer hangs the OS
/// (stage A, roadmap A.7). The ring-0 exec path still spins afterwards
/// (documented v1 limitation).
#[cfg(not(test))]
#[panic_handler]
fn panic(info: &core::panic::PanicInfo<'_>) -> ! {
    crate::abi::stdout_line(&crate::__format(format_args!("app panic: {info}")));
    crate::sys::process::exit(-1);
    loop {
        core::hint::spin_loop();
    }
}
